#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class connection : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertFeedBack_Table(FeedBack_Table instance);
  partial void UpdateFeedBack_Table(FeedBack_Table instance);
  partial void DeleteFeedBack_Table(FeedBack_Table instance);
  partial void InsertPackageBookingTable(PackageBookingTable instance);
  partial void UpdatePackageBookingTable(PackageBookingTable instance);
  partial void DeletePackageBookingTable(PackageBookingTable instance);
  partial void InsertPackageTable(PackageTable instance);
  partial void UpdatePackageTable(PackageTable instance);
  partial void DeletePackageTable(PackageTable instance);
  partial void InsertResturantTable(ResturantTable instance);
  partial void UpdateResturantTable(ResturantTable instance);
  partial void DeleteResturantTable(ResturantTable instance);
  partial void Insertroom_booking(room_booking instance);
  partial void Updateroom_booking(room_booking instance);
  partial void Deleteroom_booking(room_booking instance);
  partial void Insertroom_facility_table(room_facility_table instance);
  partial void Updateroom_facility_table(room_facility_table instance);
  partial void Deleteroom_facility_table(room_facility_table instance);
  partial void Insertroom_gallery_table(room_gallery_table instance);
  partial void Updateroom_gallery_table(room_gallery_table instance);
  partial void Deleteroom_gallery_table(room_gallery_table instance);
  partial void Insertroom_table(room_table instance);
  partial void Updateroom_table(room_table instance);
  partial void Deleteroom_table(room_table instance);
  partial void InsertSystemTable(SystemTable instance);
  partial void UpdateSystemTable(SystemTable instance);
  partial void DeleteSystemTable(SystemTable instance);
  partial void Insertpayment(payment instance);
  partial void Updatepayment(payment instance);
  partial void Deletepayment(payment instance);
  partial void InsertResturantBookingTable(ResturantBookingTable instance);
  partial void UpdateResturantBookingTable(ResturantBookingTable instance);
  partial void DeleteResturantBookingTable(ResturantBookingTable instance);
  partial void InsertSpa_Table(Spa_Table instance);
  partial void UpdateSpa_Table(Spa_Table instance);
  partial void DeleteSpa_Table(Spa_Table instance);
  partial void InsertUser_Login_Table(User_Login_Table instance);
  partial void UpdateUser_Login_Table(User_Login_Table instance);
  partial void DeleteUser_Login_Table(User_Login_Table instance);
  partial void InsertUser_Registration_Table(User_Registration_Table instance);
  partial void UpdateUser_Registration_Table(User_Registration_Table instance);
  partial void DeleteUser_Registration_Table(User_Registration_Table instance);
  #endregion
	
	public connection() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public connection(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public connection(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public connection(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public connection(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<FeedBack_Table> FeedBack_Tables
	{
		get
		{
			return this.GetTable<FeedBack_Table>();
		}
	}
	
	public System.Data.Linq.Table<PackageBookingTable> PackageBookingTables
	{
		get
		{
			return this.GetTable<PackageBookingTable>();
		}
	}
	
	public System.Data.Linq.Table<PackageTable> PackageTables
	{
		get
		{
			return this.GetTable<PackageTable>();
		}
	}
	
	public System.Data.Linq.Table<ResturantTable> ResturantTables
	{
		get
		{
			return this.GetTable<ResturantTable>();
		}
	}
	
	public System.Data.Linq.Table<room_booking> room_bookings
	{
		get
		{
			return this.GetTable<room_booking>();
		}
	}
	
	public System.Data.Linq.Table<room_facility_table> room_facility_tables
	{
		get
		{
			return this.GetTable<room_facility_table>();
		}
	}
	
	public System.Data.Linq.Table<room_gallery_table> room_gallery_tables
	{
		get
		{
			return this.GetTable<room_gallery_table>();
		}
	}
	
	public System.Data.Linq.Table<room_table> room_tables
	{
		get
		{
			return this.GetTable<room_table>();
		}
	}
	
	public System.Data.Linq.Table<SystemTable> SystemTables
	{
		get
		{
			return this.GetTable<SystemTable>();
		}
	}
	
	public System.Data.Linq.Table<payment> payments
	{
		get
		{
			return this.GetTable<payment>();
		}
	}
	
	public System.Data.Linq.Table<ResturantBookingTable> ResturantBookingTables
	{
		get
		{
			return this.GetTable<ResturantBookingTable>();
		}
	}
	
	public System.Data.Linq.Table<Spa_Table> Spa_Tables
	{
		get
		{
			return this.GetTable<Spa_Table>();
		}
	}
	
	public System.Data.Linq.Table<User_Login_Table> User_Login_Tables
	{
		get
		{
			return this.GetTable<User_Login_Table>();
		}
	}
	
	public System.Data.Linq.Table<User_Registration_Table> User_Registration_Tables
	{
		get
		{
			return this.GetTable<User_Registration_Table>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[FeedBack Table]")]
public partial class FeedBack_Table : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _Name;
	
	private string _Message;
	
	private string _Email;
	
	private string _Mobile;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    #endregion
	
	public FeedBack_Table()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(500)")]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this.OnMessageChanging(value);
				this.SendPropertyChanging();
				this._Message = value;
				this.SendPropertyChanged("Message");
				this.OnMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(50)")]
	public string Mobile
	{
		get
		{
			return this._Mobile;
		}
		set
		{
			if ((this._Mobile != value))
			{
				this.OnMobileChanging(value);
				this.SendPropertyChanging();
				this._Mobile = value;
				this.SendPropertyChanged("Mobile");
				this.OnMobileChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PackageBookingTable")]
public partial class PackageBookingTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _booking_id;
	
	private string _name;
	
	private string _mobile;
	
	private string _email;
	
	private string _gender;
	
	private string _age;
	
	private string _city;
	
	private System.Nullable<int> _PackageId;
	
	private string _date;
	
	private string _time;
	
	private string _Status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbooking_idChanging(int value);
    partial void Onbooking_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnageChanging(string value);
    partial void OnageChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnPackageIdChanging(System.Nullable<int> value);
    partial void OnPackageIdChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
	
	public PackageBookingTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booking_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int booking_id
	{
		get
		{
			return this._booking_id;
		}
		set
		{
			if ((this._booking_id != value))
			{
				this.Onbooking_idChanging(value);
				this.SendPropertyChanging();
				this._booking_id = value;
				this.SendPropertyChanged("booking_id");
				this.Onbooking_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="VarChar(50)")]
	public string mobile
	{
		get
		{
			return this._mobile;
		}
		set
		{
			if ((this._mobile != value))
			{
				this.OnmobileChanging(value);
				this.SendPropertyChanging();
				this._mobile = value;
				this.SendPropertyChanged("mobile");
				this.OnmobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50)")]
	public string gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="VarChar(50)")]
	public string age
	{
		get
		{
			return this._age;
		}
		set
		{
			if ((this._age != value))
			{
				this.OnageChanging(value);
				this.SendPropertyChanging();
				this._age = value;
				this.SendPropertyChanged("age");
				this.OnageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageId", DbType="Int")]
	public System.Nullable<int> PackageId
	{
		get
		{
			return this._PackageId;
		}
		set
		{
			if ((this._PackageId != value))
			{
				this.OnPackageIdChanging(value);
				this.SendPropertyChanging();
				this._PackageId = value;
				this.SendPropertyChanged("PackageId");
				this.OnPackageIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="VarChar(50)")]
	public string date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="VarChar(50)")]
	public string time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this.OntimeChanging(value);
				this.SendPropertyChanging();
				this._time = value;
				this.SendPropertyChanged("time");
				this.OntimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PackageTable")]
public partial class PackageTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _PackageType;
	
	private string _image1;
	
	private string _image2;
	
	private string _image3;
	
	private string _image4;
	
	private string _image5;
	
	private System.Nullable<decimal> _Price;
	
	private string _description;
	
	private string _description1;
	
	private string _description2;
	
	private string _description3;
	
	private string _description4;
	
	private string _description5;
	
	private string _description6;
	
	private string _description7;
	
	private string _description8;
	
	private string _description9;
	
	private string _description10;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPackageTypeChanging(string value);
    partial void OnPackageTypeChanged();
    partial void Onimage1Changing(string value);
    partial void Onimage1Changed();
    partial void Onimage2Changing(string value);
    partial void Onimage2Changed();
    partial void Onimage3Changing(string value);
    partial void Onimage3Changed();
    partial void Onimage4Changing(string value);
    partial void Onimage4Changed();
    partial void Onimage5Changing(string value);
    partial void Onimage5Changed();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Ondescription1Changing(string value);
    partial void Ondescription1Changed();
    partial void Ondescription2Changing(string value);
    partial void Ondescription2Changed();
    partial void Ondescription3Changing(string value);
    partial void Ondescription3Changed();
    partial void Ondescription4Changing(string value);
    partial void Ondescription4Changed();
    partial void Ondescription5Changing(string value);
    partial void Ondescription5Changed();
    partial void Ondescription6Changing(string value);
    partial void Ondescription6Changed();
    partial void Ondescription7Changing(string value);
    partial void Ondescription7Changed();
    partial void Ondescription8Changing(string value);
    partial void Ondescription8Changed();
    partial void Ondescription9Changing(string value);
    partial void Ondescription9Changed();
    partial void Ondescription10Changing(string value);
    partial void Ondescription10Changed();
    #endregion
	
	public PackageTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageType", DbType="VarChar(50)")]
	public string PackageType
	{
		get
		{
			return this._PackageType;
		}
		set
		{
			if ((this._PackageType != value))
			{
				this.OnPackageTypeChanging(value);
				this.SendPropertyChanging();
				this._PackageType = value;
				this.SendPropertyChanged("PackageType");
				this.OnPackageTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image1", DbType="VarChar(50)")]
	public string image1
	{
		get
		{
			return this._image1;
		}
		set
		{
			if ((this._image1 != value))
			{
				this.Onimage1Changing(value);
				this.SendPropertyChanging();
				this._image1 = value;
				this.SendPropertyChanged("image1");
				this.Onimage1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image2", DbType="VarChar(50)")]
	public string image2
	{
		get
		{
			return this._image2;
		}
		set
		{
			if ((this._image2 != value))
			{
				this.Onimage2Changing(value);
				this.SendPropertyChanging();
				this._image2 = value;
				this.SendPropertyChanged("image2");
				this.Onimage2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image3", DbType="VarChar(50)")]
	public string image3
	{
		get
		{
			return this._image3;
		}
		set
		{
			if ((this._image3 != value))
			{
				this.Onimage3Changing(value);
				this.SendPropertyChanging();
				this._image3 = value;
				this.SendPropertyChanged("image3");
				this.Onimage3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image4", DbType="VarChar(50)")]
	public string image4
	{
		get
		{
			return this._image4;
		}
		set
		{
			if ((this._image4 != value))
			{
				this.Onimage4Changing(value);
				this.SendPropertyChanging();
				this._image4 = value;
				this.SendPropertyChanged("image4");
				this.Onimage4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image5", DbType="VarChar(50)")]
	public string image5
	{
		get
		{
			return this._image5;
		}
		set
		{
			if ((this._image5 != value))
			{
				this.Onimage5Changing(value);
				this.SendPropertyChanging();
				this._image5 = value;
				this.SendPropertyChanged("image5");
				this.Onimage5Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description1", DbType="VarChar(MAX)")]
	public string description1
	{
		get
		{
			return this._description1;
		}
		set
		{
			if ((this._description1 != value))
			{
				this.Ondescription1Changing(value);
				this.SendPropertyChanging();
				this._description1 = value;
				this.SendPropertyChanged("description1");
				this.Ondescription1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description2", DbType="VarChar(MAX)")]
	public string description2
	{
		get
		{
			return this._description2;
		}
		set
		{
			if ((this._description2 != value))
			{
				this.Ondescription2Changing(value);
				this.SendPropertyChanging();
				this._description2 = value;
				this.SendPropertyChanged("description2");
				this.Ondescription2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description3", DbType="VarChar(MAX)")]
	public string description3
	{
		get
		{
			return this._description3;
		}
		set
		{
			if ((this._description3 != value))
			{
				this.Ondescription3Changing(value);
				this.SendPropertyChanging();
				this._description3 = value;
				this.SendPropertyChanged("description3");
				this.Ondescription3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description4", DbType="VarChar(MAX)")]
	public string description4
	{
		get
		{
			return this._description4;
		}
		set
		{
			if ((this._description4 != value))
			{
				this.Ondescription4Changing(value);
				this.SendPropertyChanging();
				this._description4 = value;
				this.SendPropertyChanged("description4");
				this.Ondescription4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description5", DbType="VarChar(MAX)")]
	public string description5
	{
		get
		{
			return this._description5;
		}
		set
		{
			if ((this._description5 != value))
			{
				this.Ondescription5Changing(value);
				this.SendPropertyChanging();
				this._description5 = value;
				this.SendPropertyChanged("description5");
				this.Ondescription5Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description6", DbType="VarChar(MAX)")]
	public string description6
	{
		get
		{
			return this._description6;
		}
		set
		{
			if ((this._description6 != value))
			{
				this.Ondescription6Changing(value);
				this.SendPropertyChanging();
				this._description6 = value;
				this.SendPropertyChanged("description6");
				this.Ondescription6Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description7", DbType="VarChar(MAX)")]
	public string description7
	{
		get
		{
			return this._description7;
		}
		set
		{
			if ((this._description7 != value))
			{
				this.Ondescription7Changing(value);
				this.SendPropertyChanging();
				this._description7 = value;
				this.SendPropertyChanged("description7");
				this.Ondescription7Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description8", DbType="VarChar(MAX)")]
	public string description8
	{
		get
		{
			return this._description8;
		}
		set
		{
			if ((this._description8 != value))
			{
				this.Ondescription8Changing(value);
				this.SendPropertyChanging();
				this._description8 = value;
				this.SendPropertyChanged("description8");
				this.Ondescription8Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description9", DbType="VarChar(MAX)")]
	public string description9
	{
		get
		{
			return this._description9;
		}
		set
		{
			if ((this._description9 != value))
			{
				this.Ondescription9Changing(value);
				this.SendPropertyChanging();
				this._description9 = value;
				this.SendPropertyChanged("description9");
				this.Ondescription9Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description10", DbType="VarChar(MAX)")]
	public string description10
	{
		get
		{
			return this._description10;
		}
		set
		{
			if ((this._description10 != value))
			{
				this.Ondescription10Changing(value);
				this.SendPropertyChanging();
				this._description10 = value;
				this.SendPropertyChanged("description10");
				this.Ondescription10Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResturantTable")]
public partial class ResturantTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _ResturantType;
	
	private string _image1;
	
	private string _image2;
	
	private string _image3;
	
	private string _image4;
	
	private string _image5;
	
	private string _image6;
	
	private System.Nullable<decimal> _Price;
	
	private string _description;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnResturantTypeChanging(string value);
    partial void OnResturantTypeChanged();
    partial void Onimage1Changing(string value);
    partial void Onimage1Changed();
    partial void Onimage2Changing(string value);
    partial void Onimage2Changed();
    partial void Onimage3Changing(string value);
    partial void Onimage3Changed();
    partial void Onimage4Changing(string value);
    partial void Onimage4Changed();
    partial void Onimage5Changing(string value);
    partial void Onimage5Changed();
    partial void Onimage6Changing(string value);
    partial void Onimage6Changed();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
	
	public ResturantTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResturantType", DbType="VarChar(50)")]
	public string ResturantType
	{
		get
		{
			return this._ResturantType;
		}
		set
		{
			if ((this._ResturantType != value))
			{
				this.OnResturantTypeChanging(value);
				this.SendPropertyChanging();
				this._ResturantType = value;
				this.SendPropertyChanged("ResturantType");
				this.OnResturantTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image1", DbType="VarChar(50)")]
	public string image1
	{
		get
		{
			return this._image1;
		}
		set
		{
			if ((this._image1 != value))
			{
				this.Onimage1Changing(value);
				this.SendPropertyChanging();
				this._image1 = value;
				this.SendPropertyChanged("image1");
				this.Onimage1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image2", DbType="VarChar(50)")]
	public string image2
	{
		get
		{
			return this._image2;
		}
		set
		{
			if ((this._image2 != value))
			{
				this.Onimage2Changing(value);
				this.SendPropertyChanging();
				this._image2 = value;
				this.SendPropertyChanged("image2");
				this.Onimage2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image3", DbType="VarChar(50)")]
	public string image3
	{
		get
		{
			return this._image3;
		}
		set
		{
			if ((this._image3 != value))
			{
				this.Onimage3Changing(value);
				this.SendPropertyChanging();
				this._image3 = value;
				this.SendPropertyChanged("image3");
				this.Onimage3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image4", DbType="VarChar(50)")]
	public string image4
	{
		get
		{
			return this._image4;
		}
		set
		{
			if ((this._image4 != value))
			{
				this.Onimage4Changing(value);
				this.SendPropertyChanging();
				this._image4 = value;
				this.SendPropertyChanged("image4");
				this.Onimage4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image5", DbType="VarChar(50)")]
	public string image5
	{
		get
		{
			return this._image5;
		}
		set
		{
			if ((this._image5 != value))
			{
				this.Onimage5Changing(value);
				this.SendPropertyChanging();
				this._image5 = value;
				this.SendPropertyChanged("image5");
				this.Onimage5Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image6", DbType="VarChar(50)")]
	public string image6
	{
		get
		{
			return this._image6;
		}
		set
		{
			if ((this._image6 != value))
			{
				this.Onimage6Changing(value);
				this.SendPropertyChanging();
				this._image6 = value;
				this.SendPropertyChanged("image6");
				this.Onimage6Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[room booking]")]
public partial class room_booking : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _booking_id;
	
	private string _name;
	
	private System.Nullable<decimal> _mobile;
	
	private string _email_id;
	
	private string _room;
	
	private System.Nullable<int> _noofrooms;
	
	private System.Nullable<int> _noofperson;
	
	private string _idproof;
	
	private string _city;
	
	private System.Nullable<int> _age;
	
	private string _gender;
	
	private string _date;
	
	private string _time;
	
	private string _Status;
	
	private System.Nullable<decimal> _amount;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbooking_idChanging(int value);
    partial void Onbooking_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnmobileChanging(System.Nullable<decimal> value);
    partial void OnmobileChanged();
    partial void Onemail_idChanging(string value);
    partial void Onemail_idChanged();
    partial void OnroomChanging(string value);
    partial void OnroomChanged();
    partial void OnnoofroomsChanging(System.Nullable<int> value);
    partial void OnnoofroomsChanged();
    partial void OnnoofpersonChanging(System.Nullable<int> value);
    partial void OnnoofpersonChanged();
    partial void OnidproofChanging(string value);
    partial void OnidproofChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnamountChanging(System.Nullable<decimal> value);
    partial void OnamountChanged();
    #endregion
	
	public room_booking()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booking_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int booking_id
	{
		get
		{
			return this._booking_id;
		}
		set
		{
			if ((this._booking_id != value))
			{
				this.Onbooking_idChanging(value);
				this.SendPropertyChanging();
				this._booking_id = value;
				this.SendPropertyChanged("booking_id");
				this.Onbooking_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> mobile
	{
		get
		{
			return this._mobile;
		}
		set
		{
			if ((this._mobile != value))
			{
				this.OnmobileChanging(value);
				this.SendPropertyChanging();
				this._mobile = value;
				this.SendPropertyChanged("mobile");
				this.OnmobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_id", DbType="VarChar(50)")]
	public string email_id
	{
		get
		{
			return this._email_id;
		}
		set
		{
			if ((this._email_id != value))
			{
				this.Onemail_idChanging(value);
				this.SendPropertyChanging();
				this._email_id = value;
				this.SendPropertyChanged("email_id");
				this.Onemail_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room", DbType="VarChar(50)")]
	public string room
	{
		get
		{
			return this._room;
		}
		set
		{
			if ((this._room != value))
			{
				this.OnroomChanging(value);
				this.SendPropertyChanging();
				this._room = value;
				this.SendPropertyChanged("room");
				this.OnroomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noofrooms", DbType="Int")]
	public System.Nullable<int> noofrooms
	{
		get
		{
			return this._noofrooms;
		}
		set
		{
			if ((this._noofrooms != value))
			{
				this.OnnoofroomsChanging(value);
				this.SendPropertyChanging();
				this._noofrooms = value;
				this.SendPropertyChanged("noofrooms");
				this.OnnoofroomsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noofperson", DbType="Int")]
	public System.Nullable<int> noofperson
	{
		get
		{
			return this._noofperson;
		}
		set
		{
			if ((this._noofperson != value))
			{
				this.OnnoofpersonChanging(value);
				this.SendPropertyChanging();
				this._noofperson = value;
				this.SendPropertyChanged("noofperson");
				this.OnnoofpersonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idproof", DbType="VarChar(50)")]
	public string idproof
	{
		get
		{
			return this._idproof;
		}
		set
		{
			if ((this._idproof != value))
			{
				this.OnidproofChanging(value);
				this.SendPropertyChanging();
				this._idproof = value;
				this.SendPropertyChanged("idproof");
				this.OnidproofChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
	public System.Nullable<int> age
	{
		get
		{
			return this._age;
		}
		set
		{
			if ((this._age != value))
			{
				this.OnageChanging(value);
				this.SendPropertyChanging();
				this._age = value;
				this.SendPropertyChanged("age");
				this.OnageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50)")]
	public string gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="VarChar(50)")]
	public string date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="VarChar(50)")]
	public string time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this.OntimeChanging(value);
				this.SendPropertyChanging();
				this._time = value;
				this.SendPropertyChanged("time");
				this.OntimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this.OnamountChanging(value);
				this.SendPropertyChanging();
				this._amount = value;
				this.SendPropertyChanged("amount");
				this.OnamountChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[room facility table]")]
public partial class room_facility_table : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _facility_id;
	
	private System.Nullable<int> _room_id;
	
	private string _facility;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfacility_idChanging(int value);
    partial void Onfacility_idChanged();
    partial void Onroom_idChanging(System.Nullable<int> value);
    partial void Onroom_idChanged();
    partial void OnfacilityChanging(string value);
    partial void OnfacilityChanged();
    #endregion
	
	public room_facility_table()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facility_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int facility_id
	{
		get
		{
			return this._facility_id;
		}
		set
		{
			if ((this._facility_id != value))
			{
				this.Onfacility_idChanging(value);
				this.SendPropertyChanging();
				this._facility_id = value;
				this.SendPropertyChanged("facility_id");
				this.Onfacility_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_id", DbType="Int")]
	public System.Nullable<int> room_id
	{
		get
		{
			return this._room_id;
		}
		set
		{
			if ((this._room_id != value))
			{
				this.Onroom_idChanging(value);
				this.SendPropertyChanging();
				this._room_id = value;
				this.SendPropertyChanged("room_id");
				this.Onroom_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facility", DbType="VarChar(50)")]
	public string facility
	{
		get
		{
			return this._facility;
		}
		set
		{
			if ((this._facility != value))
			{
				this.OnfacilityChanging(value);
				this.SendPropertyChanging();
				this._facility = value;
				this.SendPropertyChanged("facility");
				this.OnfacilityChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[room gallery table]")]
public partial class room_gallery_table : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _galleryid;
	
	private System.Nullable<int> _roomid;
	
	private string _image;
	
	private string _caption;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngalleryidChanging(int value);
    partial void OngalleryidChanged();
    partial void OnroomidChanging(System.Nullable<int> value);
    partial void OnroomidChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OncaptionChanging(string value);
    partial void OncaptionChanged();
    #endregion
	
	public room_gallery_table()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_galleryid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int galleryid
	{
		get
		{
			return this._galleryid;
		}
		set
		{
			if ((this._galleryid != value))
			{
				this.OngalleryidChanging(value);
				this.SendPropertyChanging();
				this._galleryid = value;
				this.SendPropertyChanged("galleryid");
				this.OngalleryidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roomid", DbType="Int")]
	public System.Nullable<int> roomid
	{
		get
		{
			return this._roomid;
		}
		set
		{
			if ((this._roomid != value))
			{
				this.OnroomidChanging(value);
				this.SendPropertyChanging();
				this._roomid = value;
				this.SendPropertyChanged("roomid");
				this.OnroomidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(50)")]
	public string image
	{
		get
		{
			return this._image;
		}
		set
		{
			if ((this._image != value))
			{
				this.OnimageChanging(value);
				this.SendPropertyChanging();
				this._image = value;
				this.SendPropertyChanged("image");
				this.OnimageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caption", DbType="VarChar(150)")]
	public string caption
	{
		get
		{
			return this._caption;
		}
		set
		{
			if ((this._caption != value))
			{
				this.OncaptionChanging(value);
				this.SendPropertyChanging();
				this._caption = value;
				this.SendPropertyChanged("caption");
				this.OncaptionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[room table]")]
public partial class room_table : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Roomid;
	
	private string _roomtype;
	
	private string _description;
	
	private string _roomrent;
	
	private string _image;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoomidChanging(int value);
    partial void OnRoomidChanged();
    partial void OnroomtypeChanging(string value);
    partial void OnroomtypeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnroomrentChanging(string value);
    partial void OnroomrentChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    #endregion
	
	public room_table()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Roomid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Roomid
	{
		get
		{
			return this._Roomid;
		}
		set
		{
			if ((this._Roomid != value))
			{
				this.OnRoomidChanging(value);
				this.SendPropertyChanging();
				this._Roomid = value;
				this.SendPropertyChanged("Roomid");
				this.OnRoomidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roomtype", DbType="VarChar(50)")]
	public string roomtype
	{
		get
		{
			return this._roomtype;
		}
		set
		{
			if ((this._roomtype != value))
			{
				this.OnroomtypeChanging(value);
				this.SendPropertyChanging();
				this._roomtype = value;
				this.SendPropertyChanged("roomtype");
				this.OnroomtypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roomrent", DbType="VarChar(50)")]
	public string roomrent
	{
		get
		{
			return this._roomrent;
		}
		set
		{
			if ((this._roomrent != value))
			{
				this.OnroomrentChanging(value);
				this.SendPropertyChanging();
				this._roomrent = value;
				this.SendPropertyChanged("roomrent");
				this.OnroomrentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(100)")]
	public string image
	{
		get
		{
			return this._image;
		}
		set
		{
			if ((this._image != value))
			{
				this.OnimageChanging(value);
				this.SendPropertyChanging();
				this._image = value;
				this.SendPropertyChanged("image");
				this.OnimageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SystemTable")]
public partial class SystemTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _ImageId;
	
	private System.Nullable<int> _BookingId;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnImageIdChanging(System.Nullable<int> value);
    partial void OnImageIdChanged();
    partial void OnBookingIdChanging(System.Nullable<int> value);
    partial void OnBookingIdChanged();
    #endregion
	
	public SystemTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageId", DbType="Int")]
	public System.Nullable<int> ImageId
	{
		get
		{
			return this._ImageId;
		}
		set
		{
			if ((this._ImageId != value))
			{
				this.OnImageIdChanging(value);
				this.SendPropertyChanging();
				this._ImageId = value;
				this.SendPropertyChanged("ImageId");
				this.OnImageIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingId", DbType="Int")]
	public System.Nullable<int> BookingId
	{
		get
		{
			return this._BookingId;
		}
		set
		{
			if ((this._BookingId != value))
			{
				this.OnBookingIdChanging(value);
				this.SendPropertyChanging();
				this._BookingId = value;
				this.SendPropertyChanged("BookingId");
				this.OnBookingIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.payment")]
public partial class payment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _payment_id;
	
	private System.Nullable<int> _booking_id;
	
	private System.Nullable<decimal> _amount;
	
	private string _cardtype;
	
	private System.Nullable<decimal> _cardnumber;
	
	private string _nameoncard;
	
	private string _expdate;
	
	private System.Nullable<int> _cvv_code;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpayment_idChanging(int value);
    partial void Onpayment_idChanged();
    partial void Onbooking_idChanging(System.Nullable<int> value);
    partial void Onbooking_idChanged();
    partial void OnamountChanging(System.Nullable<decimal> value);
    partial void OnamountChanged();
    partial void OncardtypeChanging(string value);
    partial void OncardtypeChanged();
    partial void OncardnumberChanging(System.Nullable<decimal> value);
    partial void OncardnumberChanged();
    partial void OnnameoncardChanging(string value);
    partial void OnnameoncardChanged();
    partial void OnexpdateChanging(string value);
    partial void OnexpdateChanged();
    partial void Oncvv_codeChanging(System.Nullable<int> value);
    partial void Oncvv_codeChanged();
    #endregion
	
	public payment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int payment_id
	{
		get
		{
			return this._payment_id;
		}
		set
		{
			if ((this._payment_id != value))
			{
				this.Onpayment_idChanging(value);
				this.SendPropertyChanging();
				this._payment_id = value;
				this.SendPropertyChanged("payment_id");
				this.Onpayment_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booking_id", DbType="Int")]
	public System.Nullable<int> booking_id
	{
		get
		{
			return this._booking_id;
		}
		set
		{
			if ((this._booking_id != value))
			{
				this.Onbooking_idChanging(value);
				this.SendPropertyChanging();
				this._booking_id = value;
				this.SendPropertyChanged("booking_id");
				this.Onbooking_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this.OnamountChanging(value);
				this.SendPropertyChanging();
				this._amount = value;
				this.SendPropertyChanged("amount");
				this.OnamountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cardtype", DbType="VarChar(50)")]
	public string cardtype
	{
		get
		{
			return this._cardtype;
		}
		set
		{
			if ((this._cardtype != value))
			{
				this.OncardtypeChanging(value);
				this.SendPropertyChanging();
				this._cardtype = value;
				this.SendPropertyChanged("cardtype");
				this.OncardtypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cardnumber", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> cardnumber
	{
		get
		{
			return this._cardnumber;
		}
		set
		{
			if ((this._cardnumber != value))
			{
				this.OncardnumberChanging(value);
				this.SendPropertyChanging();
				this._cardnumber = value;
				this.SendPropertyChanged("cardnumber");
				this.OncardnumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameoncard", DbType="VarChar(50)")]
	public string nameoncard
	{
		get
		{
			return this._nameoncard;
		}
		set
		{
			if ((this._nameoncard != value))
			{
				this.OnnameoncardChanging(value);
				this.SendPropertyChanging();
				this._nameoncard = value;
				this.SendPropertyChanged("nameoncard");
				this.OnnameoncardChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expdate", DbType="VarChar(50)")]
	public string expdate
	{
		get
		{
			return this._expdate;
		}
		set
		{
			if ((this._expdate != value))
			{
				this.OnexpdateChanging(value);
				this.SendPropertyChanging();
				this._expdate = value;
				this.SendPropertyChanged("expdate");
				this.OnexpdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cvv_code", DbType="Int")]
	public System.Nullable<int> cvv_code
	{
		get
		{
			return this._cvv_code;
		}
		set
		{
			if ((this._cvv_code != value))
			{
				this.Oncvv_codeChanging(value);
				this.SendPropertyChanging();
				this._cvv_code = value;
				this.SendPropertyChanged("cvv_code");
				this.Oncvv_codeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResturantBookingTable")]
public partial class ResturantBookingTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _booking_id;
	
	private string _name;
	
	private string _mobile;
	
	private string _email;
	
	private string _gender;
	
	private string _age;
	
	private string _city;
	
	private string _Resturantname;
	
	private string _date;
	
	private string _time;
	
	private string _Status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbooking_idChanging(int value);
    partial void Onbooking_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnageChanging(string value);
    partial void OnageChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnResturantnameChanging(string value);
    partial void OnResturantnameChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
	
	public ResturantBookingTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booking_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int booking_id
	{
		get
		{
			return this._booking_id;
		}
		set
		{
			if ((this._booking_id != value))
			{
				this.Onbooking_idChanging(value);
				this.SendPropertyChanging();
				this._booking_id = value;
				this.SendPropertyChanged("booking_id");
				this.Onbooking_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="VarChar(50)")]
	public string mobile
	{
		get
		{
			return this._mobile;
		}
		set
		{
			if ((this._mobile != value))
			{
				this.OnmobileChanging(value);
				this.SendPropertyChanging();
				this._mobile = value;
				this.SendPropertyChanged("mobile");
				this.OnmobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50)")]
	public string gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="VarChar(50)")]
	public string age
	{
		get
		{
			return this._age;
		}
		set
		{
			if ((this._age != value))
			{
				this.OnageChanging(value);
				this.SendPropertyChanging();
				this._age = value;
				this.SendPropertyChanged("age");
				this.OnageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resturantname", DbType="VarChar(50)")]
	public string Resturantname
	{
		get
		{
			return this._Resturantname;
		}
		set
		{
			if ((this._Resturantname != value))
			{
				this.OnResturantnameChanging(value);
				this.SendPropertyChanging();
				this._Resturantname = value;
				this.SendPropertyChanged("Resturantname");
				this.OnResturantnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="VarChar(50)")]
	public string date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="VarChar(50)")]
	public string time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this.OntimeChanging(value);
				this.SendPropertyChanging();
				this._time = value;
				this.SendPropertyChanged("time");
				this.OntimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Spa Table]")]
public partial class Spa_Table : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _type;
	
	private System.Nullable<decimal> _Price;
	
	private string _Description;
	
	private string _image;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    #endregion
	
	public Spa_Table()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(50)")]
	public string image
	{
		get
		{
			return this._image;
		}
		set
		{
			if ((this._image != value))
			{
				this.OnimageChanging(value);
				this.SendPropertyChanging();
				this._image = value;
				this.SendPropertyChanged("image");
				this.OnimageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User Login Table]")]
public partial class User_Login_Table : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _username;
	
	private string _password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
	
	public User_Login_Table()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User Registration Table]")]
public partial class User_Registration_Table : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Username;
	
	private string _password;
	
	private string _Email;
	
	private string _mobile;
	
	private int _id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
	
	public User_Registration_Table()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
	public string Username
	{
		get
		{
			return this._Username;
		}
		set
		{
			if ((this._Username != value))
			{
				this.OnUsernameChanging(value);
				this.SendPropertyChanging();
				this._Username = value;
				this.SendPropertyChanged("Username");
				this.OnUsernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="VarChar(50)")]
	public string mobile
	{
		get
		{
			return this._mobile;
		}
		set
		{
			if ((this._mobile != value))
			{
				this.OnmobileChanging(value);
				this.SendPropertyChanging();
				this._mobile = value;
				this.SendPropertyChanged("mobile");
				this.OnmobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
